name: 'Install dependencies'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Get pnpm cache
      id: pnpm-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline
